### ISSUE TITLE
empty string decoded as atom undefined

### ISSUE THREAD

**Issue by vesvalo** [processone/xml#6] opened 2015-03-20 15:57 UTC
xmlrpc_codec decodes `<string/>` to atom **undefined**:
`decode_string_cdata(__TopXMLNS, <<>>) -> undefined;`

We are using ejabberd-contrib/mod_admin_extra:add_rosteritem, and if we pass empty string to xmlrpc, we get the following error:
Error: the command "add_rosteritem" requires 1 more argument.

Please change the code this way:
`decode_string_cdata(__TopXMLNS, <<>>) -> <<>>;`

**Comment by mremond** [comment] 2015-03-20 16:22
Thanks, we will have a look :+1:

**Comment by zinid** [comment] 2015-03-27 10:29
The issue is fixed in 98444ecea063ac55751667c198c438ab4cf63275

**Closed by zinid** 2015-03-27 10:29 UTC
